DECLARE @DB NVARCHAR(50) = N'%%'
DECLARE @SCHEMA NVARCHAR(50) = N'%%'
DECLARE @TABLE NVARCHAR(50) = N'%A%'

SELECT  'DROP TABLE ' + TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME
FROM    INFORMATION_SCHEMA.TABLES
WHERE   TABLE_CATALOG LIKE @DB
        AND TABLE_SCHEMA LIKE @SCHEMA
        AND TABLE_NAME LIKE @TABLE