
sp_helprotect

sp_readerrorlog

DBCC SQLPERF(LOGSPACE)

DBCC LOG('Master',4)

select * from ::fn_dblog(default, default)
--http://rusanu.com/2014/03/10/how-to-read-and-interpret-the-sql-server-log/
--Transaction SID
--SELECT * FROM sys.server_principals where sid = 0x0105000000000005150000005D28F57FD53AD8354354E02A61F21A00
DBCC LOGINFO



SELECT
    *
FROM
    fn_dump_dblog (
        NULL, NULL, N'DISK', 1, N'D:\Football_log - Read.ldf',
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);