// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ConsoleApplication2
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\v-thzhu\Documents\Visual Studio 2013\Projects\AdventureWork\ConsoleApplication2\DerivedTemplate1.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class DerivedTemplate1 : AbstractBaseTemplate1
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "C:\Users\v-thzhu\Documents\Visual Studio 2013\Projects\AdventureWork\ConsoleApplication2\DerivedTemplate1.tt"
 
  // Set the base template properties:
  base.Description = "Description for this derived class"; 

  // Run the base template:
  base.TransformText();



            
            #line default
            #line hidden
            this.Write("End material for DerivedTemplate1.\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 13 "C:\Users\v-thzhu\Documents\Visual Studio 2013\Projects\AdventureWork\ConsoleApplication2\DerivedTemplate1.tt"

// Provide a fragment specific to this derived template:

protected override void SpecificFragment(int n)
{

        
        #line default
        #line hidden
        
        #line 18 "C:\Users\v-thzhu\Documents\Visual Studio 2013\Projects\AdventureWork\ConsoleApplication2\DerivedTemplate1.tt"
this.Write("   Specific to DerivedTemplate1 : ");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\v-thzhu\Documents\Visual Studio 2013\Projects\AdventureWork\ConsoleApplication2\DerivedTemplate1.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(n));

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\v-thzhu\Documents\Visual Studio 2013\Projects\AdventureWork\ConsoleApplication2\DerivedTemplate1.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\v-thzhu\Documents\Visual Studio 2013\Projects\AdventureWork\ConsoleApplication2\DerivedTemplate1.tt"

}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
