// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ConsoleApplication2
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\v-thzhu\Documents\Visual Studio 2013\Projects\AdventureWork\ConsoleApplication2\MyTextTemplate1.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class MyTextTemplate1 : SharedFragments
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("begin 1\r\n   ");
            
            #line 3 "C:\Users\v-thzhu\Documents\Visual Studio 2013\Projects\AdventureWork\ConsoleApplication2\MyTextTemplate1.tt"
 SharedText(2); 
            
            #line default
            #line hidden
            this.Write("end 1");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
